// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Medium struct {
	ID        int64
	MediaType string
	Title     string
	Year      int64
	Overview  sql.NullString
	Director  sql.NullString
	Poster    interface{}
	Path      string
}
