// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE path = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, path)
	return err
}

const getPoster = `-- name: GetPoster :one
SELECT poster FROM media
WHERE LOWER(media.title)=LOWER(?1)
`

func (q *Queries) GetPoster(ctx context.Context, title string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getPoster, title)
	var poster interface{}
	err := row.Scan(&poster)
	return poster, err
}

const insertOrReplaceMedia = `-- name: InsertOrReplaceMedia :exec
INSERT OR REPLACE INTO media(id, media_type, title, year, overview, director, poster, path)
VALUES(?,?,?,?,?,?,?,?)
`

type InsertOrReplaceMediaParams struct {
	ID        int64
	MediaType string
	Title     string
	Year      int64
	Overview  sql.NullString
	Director  sql.NullString
	Poster    interface{}
	Path      string
}

func (q *Queries) InsertOrReplaceMedia(ctx context.Context, arg InsertOrReplaceMediaParams) error {
	_, err := q.db.ExecContext(ctx, insertOrReplaceMedia,
		arg.ID,
		arg.MediaType,
		arg.Title,
		arg.Year,
		arg.Overview,
		arg.Director,
		arg.Poster,
		arg.Path,
	)
	return err
}

const listMedia = `-- name: ListMedia :many
SELECT id, media_type, title, year, overview, director, poster, path FROM media
ORDER BY concat(year, '-01-01') DESC, title ASC
`

func (q *Queries) ListMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.Director,
			&i.Poster,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaths = `-- name: ListPaths :many
SELECT id, path FROM media
`

type ListPathsRow struct {
	ID   int64
	Path string
}

func (q *Queries) ListPaths(ctx context.Context) ([]ListPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPathsRow
	for rows.Next() {
		var i ListPathsRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookUpMedia = `-- name: LookUpMedia :many
SELECT id, media_type, title, year, overview, director, poster, path FROM media 
WHERE LOWER(media.title)=LOWER(?1) AND ABS(media.year-?2)<=?3
`

type LookUpMediaParams struct {
	Title     string
	Year      int64
	Tolerance int64
}

func (q *Queries) LookUpMedia(ctx context.Context, arg LookUpMediaParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, lookUpMedia, arg.Title, arg.Year, arg.Tolerance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.Director,
			&i.Poster,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePath = `-- name: UpdatePath :exec
UPDATE media
SET path = ?
WHERE id = ?
`

type UpdatePathParams struct {
	Path string
	ID   int64
}

func (q *Queries) UpdatePath(ctx context.Context, arg UpdatePathParams) error {
	_, err := q.db.ExecContext(ctx, updatePath, arg.Path, arg.ID)
	return err
}
