// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const getPoster = `-- name: GetPoster :one
SELECT poster FROM media
WHERE LOWER(media.title)=LOWER(?1)
`

func (q *Queries) GetPoster(ctx context.Context, title string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getPoster, title)
	var poster interface{}
	err := row.Scan(&poster)
	return poster, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, media_type, title, year, overview, director, poster, path FROM media
ORDER BY title, year ASC
`

func (q *Queries) ListMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.Director,
			&i.Poster,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookUpMedia = `-- name: LookUpMedia :many
SELECT id, media_type, title, year, overview, director, poster, path FROM media 
WHERE LOWER(media.title)=LOWER(?1) AND ABS(media.year-?2)<=?3
`

type LookUpMediaParams struct {
	Title     string
	Year      int64
	Tolerance int64
}

func (q *Queries) LookUpMedia(ctx context.Context, arg LookUpMediaParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, lookUpMedia, arg.Title, arg.Year, arg.Tolerance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.Director,
			&i.Poster,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
